# Generated by Django 4.2 on 2023-07-19 13:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('C', 'Contributor'), ('U', 'User')], default='U', max_length=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('image_title', models.CharField(max_length=200)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('watermark', models.ImageField(upload_to='watermarks/')),
                ('description', models.TextField()),
                ('taille', models.IntegerField()),
                ('format', models.CharField(max_length=200)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('orientation', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('V', 'Validated'), ('R', 'Rejected')], default='P', max_length=10)),
                ('payment_required', models.BooleanField(default=False)),
                ('licence', models.CharField(choices=[('ARR', 'Tous droits réservés'), ('PD', 'Domaine public'), ('CC', 'Creative commons'), ('CCNM', 'Creative commons - Pas de modification'), ('CCNMNCU', "Creative commons - Pas d'utilisation commerciale, Pas de modification"), ('CCNMNPCCI', "Creative commons - Pas d'utilisation commerciale, Partage des conditions initiales à l'identique"), ('CCNPCCI', "Creative commons - Partage des conditions initiales à l'identique")], default=None, max_length=100)),
                ('price', models.FloatField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image_bank.customuser')),
                ('tags', models.ManyToManyField(to='image_bank.tag')),
            ],
        ),
    ]
