# Generated by Django 4.2 on 2023-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='orientation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='taille',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='watermark',
            field=models.ImageField(null=True, upload_to='watermarks/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
