# Generated by Django 4.2 on 2023-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0002_alter_image_description_alter_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='image_bank.tag'),
        ),
    ]
