# Generated by Django 4.2 on 2023-07-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0005_licence_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='licence',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
