# Generated by Django 4.2 on 2023-09-07 14:31

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('image_bank', '0007_remove_payment_user_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='new_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
