# Generated by Django 4.2 on 2023-09-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0008_image_new_tags_alter_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
