# Generated by Django 4.2 on 2023-09-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0009_remove_image_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='watermark',
            new_name='downloaded',
        ),
    ]
