# Generated by Django 4.2 on 2023-09-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0011_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='image_bank.categorie'),
        ),
    ]
