# Generated by Django 4.2 on 2023-09-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0013_alter_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='image_title',
            new_name='image',
        ),
    ]
