# Generated by Django 4.2 on 2023-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0015_alter_payment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
